import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:URL" content="https://www.realtor.com" />
        <meta
          property="og:title"
          content="realtor.com® | Homes for Sale, Apartments &amp; Houses for Rent"
        />
        <meta
          property="og:description"
          content="Search homes for sale, new construction homes, apartments, and houses for rent. See property values. Shop mortgages."
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </div>
  );
}
